### ISSUE TITLE
Unable to create a third-party plugin for the sailfish-secrets

### ISSUE THREAD

**Issue by vityafx** [sailfishos/sailfish-secrets#117]
We need to create a plugin which can be installed later after installing sailfish-secrets plugins. However it is difficult to create one, because the headers which are exported have incorrect paths.

We created our class:

```c++
#include <Crypto/extensionplugins.h>

class Q_DECL_EXPORT CryptokiPlugin : public QObject, public Sailfish::Crypto::CryptoPlugin
{
// ...
};
```

We created our project file:

```qmake
CONFIG += plugin c++11 rtti_off qt link_pkgconfig                                                  
PKGCONFIG += sailfishcryptopluginapi
```

But we have compile errors so:

```
In file included from cryptokiplugin.h:25:0,
                 from moc_cryptokiplugin.cpp:9:
/usr/include/Sailfish/Crypto/extensionplugins.h:11:47: fatal error: SecretsPluginApi/extensionplugins.h: No such file or directory
 #include <SecretsPluginApi/extensionplugins.h>
                                               ^
compilation terminated.
make[1]: *** [moc_cryptokiplugin.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ./cryptokiplugin.h:25:0,
                 from cryptokiplugin.cpp:31:
/usr/include/Sailfish/Crypto/extensionplugins.h:11:47: fatal error: SecretsPluginApi/extensionplugins.h: No such file or directory
 #include <SecretsPluginApi/extensionplugins.h>
                                               ^
```

So there is no `SecretsPluginApi` path anywhere in `/usr/include/Sailfish` of course, but the headers inside try to include it.

**Comment by dcaliste** [comment]
For my understanding, you should install ```libsailfishcryptopluginapi-devel``` to be able to use ```#include <CryptoPluginApi/extensionplugins.h>```. This header, as you noted, depends on the secret one. But the previously mentioned RPM requires ```libsailfishsecretspluginapi-devel``` which provides this header. So it should be installed also.

By the way, the proper inclusion is now ```#include <CryptoPluginApi/extensionplugins.h>```, not only ```Crypto/```.

**Comment by vityafx** [comment]
1. **ALL** the packages from the sailfish-secrets **are** installed. From the latest state of master branch.
2. There are nothing but `Crypto/` and `Secrets/` subdirectories in the `/usr/include/Sailfish` now.

Thanks for the response.

**Comment by dcaliste** [comment]
Oups, you're right, my bad:
```
[nemo@Sailfish secrets]$ rpm -qpl libsailfishcryptopluginapi-devel-0.1.14-1.armv7hl.rpm
/usr/include/Sailfish/Crypto/extensionplugins.h
/usr/lib/libsailfishcryptopluginapi.so
/usr/lib/pkgconfig/sailfishcryptopluginapi.pc
```
The installation path for the headers is indeed ```Sailfish/Crypto/```. The same for secret case. It should be ```Sailfish/CryptoPluginApi/```. You're right, the bug lies in the installation path I guess.

**Comment by vityafx** [comment]
Of course, it does not work. There are no such paths.

**Comment by chriadam** [comment]
Thanks very much for the report, I will fix this immediately.

**Comment by chriadam** [comment]
https://github.com/sailfishos/sailfish-secrets/pull/119

**Comment by chriadam** [comment]
Also added examples in https://github.com/sailfishos/sailfish-secrets/pull/120

**Comment by vityafx** [comment]
Looks like it works now.
