### ISSUE TITLE
Cannot use requests with keyTemplate argument from QML

### ISSUE THREAD

**Issue by dcaliste** [sailfishos/sailfish-secrets#134]
Some requests take a ```keyTemplate``` argument of type ```Crypto::Key```, like the GenerateKeyRequest. But this type is declared uncreatable.

It's a bit too bad since the keyTemplate contains in fact very few data, just the name and the collection of the key to be created.

The solution may be to create a KeyTemplate type in the qml export directory and make this once instanciable from QML.

@chriadam, @Venemo any remarks? Did I miss anything?

**Comment by dcaliste** [comment]
Ah, found the CryptoManager.constructKey() call and friends…

**Comment by Venemo** [comment]
@dcaliste Unfortunately `Key` has to be uncreatable from QML, but as a workaround we added `CryptoManager.constructKey`.

**Comment by Venemo** [comment]
@dcaliste Forgot to mention: IIRC this has to do with `Q_GADGET`.

**Comment by dcaliste** [comment]
Thank you for the reply. I've seen it later. I've just proposed a PR though where I suggest to add constructKeyMetadata(), as a convenient function.
