### ISSUE TITLE
Cannot find any method of digest primitive.

### ISSUE THREAD

**Issue by Denis-Semakin** [sailfishos/sailfish-secrets#24]
Hello. I guess I already told about this. I cannot find any **digest** method in CryptoAPI, especially for plugins. I mead md5, sha1, sha256, etc... Did we miss it?

**Comment by Venemo** [comment]
@Denis-Semakin What kind of use case would you like to use the Crypto API for? Is is still under heavy development, so maybe the functionality you need was missing earlier but is added now. Can you take a second look?

Maybe this is what you were looking for?
https://github.com/sailfishos/sailfish-secrets/blob/master/lib/Crypto/calculatedigestrequest.cpp

**Comment by Denis-Semakin** [comment]
@Venemo I know about it. If you take a look on the date of my message, you may see that I've posted it 16 days ago. So @chriadam already done it.

**Comment by Venemo** [comment]
@Denis-Semakin Awesome. I'm closing this issue then! Yes I saw the date, that is why I was asking.
