### ISSUE TITLE
Provide client QML example

### ISSUE THREAD

**Issue by Venemo** [sailfishos/sailfish-secrets#57]
It would be useful to add some example code which shows how to implement a client for some specific use cases (eg. signing). What I have in mind is to have eg. some non-sailfish-specific QML code which shows the user how to do it.

This issue is a reminder to myself to add these, so I don't forget.

**Comment by Venemo** [comment]
@szopin I don't work on Sailfish Secrets anymore, but yes it is possible to use in QML only apps. We had some sample code for this a few years ago.

**Comment by chriadam** [comment]
The QML API should be considered experimental and very much subject to change.  I personally would recommend using the C++ API instead.  That said, some functionality has been exposed via QML APIs, so some subset of operations are supported as-is from QML, but many are not.  I wrote e.g. https://github.com/sailfishos/sailfish-secrets/pull/173 and it is quickly apparent that for various operations, some more wrapper stuff is needed (e.g. constructing key templates or parameter objects from QML) to support those operations is required.

**Comment by szopin** [comment]
Thank you!
